services:
  postgres-dev:
    container_name: countries-postgres-dev
    image: "postgres:16-alpine"
    ports:
      - "5433:5432"
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: countries-dev
