version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  lint-fe:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: frontend
          pkg-manager: npm
      - run:
          command: npm run lint
          working_directory: frontend
  lint-be:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: backend
          pkg-manager: npm
      - run:
          command: npm run lint
          working_directory: backend
  test-fe:
    parallelism: 2
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: frontend
          pkg-manager: npm
      - run:
          command: |
            circleci tests glob "src/**/*.test.{js,jsx,ts,tsx}" | circleci tests split --split-by=timings > /tmp/tests-to-run
            npm run test:ci $(cat /tmp/tests-to-run)
          working_directory: frontend
  test-be:
    parallelism: 2
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: backend
          pkg-manager: npm
      - run:
          command: |
            circleci tests glob "src/**/*.test.{js,jsx,ts,tsx}" | circleci tests split --split-by=timings > /tmp/tests-to-run
            npm run test:ci $(cat /tmp/tests-to-run)
          working_directory: backend
  typecheck-fe:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: frontend
          pkg-manager: npm
      - run:
          command: npm run typecheck
          working_directory: frontend
  typecheck-be:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: backend
          pkg-manager: npm
      - run:
          command: npm run typecheck
          working_directory: backend

workflows:
  default:
    jobs:
      - lint-fe
      - lint-be
      - test-fe
      - test-be
      - typecheck-fe
      - typecheck-be
