version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
  test:
    parallelism: 2
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            circleci tests glob "src/**/*.test.{js,jsx,ts,tsx}" | circleci tests split --split-by=timings > /tmp/tests-to-run
            npm run test:ci $(cat /tmp/tests-to-run)

workflows:
  default:
    jobs:
      - lint
      - test
