version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  test:
    parallelism: 2
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: |
                  circleci tests glob "src/**/*.{js,jsx,ts,tsx}" | circleci tests split --split-by=timings > /tmp/tests-to-run
                  npm run test:ci $(cat /tmp/tests-to-run)

workflows:
  default:
    jobs:
      - lint
      - test
